name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: dockerfile.run
          tags: vikings/my-web-pilot:run-$(date +%s)
    
